/* ═══════════════════════════════════════════════════════════════════════
   FIXTURE · 72 papers, 22 relevant. Full-length abstracts: the short ones
   in v2 flattered the focus lens, because with three sentences there is
   nothing for it to de-emphasise.  `nab` = no abstract → NEVER DEALT.
   ═══════════════════════════════════════════════════════════════════════ */
const P=(t,a,y,v,ab,cue,g,x={})=>({t,a,y,v,ab,cue,g,arm:x.arm||'ranked',...x});
const PAPERS=[
/* ── relevant (22) ─────────────────────────────────────────────────── */
P("Compressive strength development of alkali-activated slag binders at low curing temperature","Nkemdirim, R.; Halvorsen, A.",2024,"Cement and Concrete Research",
"Ambient placement conditions in northern Europe frequently fall well below the 20 °C at which alkali-activated systems are characterised in the laboratory, and the resulting uncertainty is a recognised barrier to site adoption.|Ground granulated blast-furnace slag activated with sodium silicate was cured at 8, 15 and 20 °C, with strength, calorimetry and pore solution chemistry followed to 90 days.|Mixes reached 41 MPa at 28 days under the coldest regime against 52 MPa at 20 °C, recovering to within 6% by 90 days.|Setting was retarded by up to nine hours, which the authors attribute to slower dissolution of the glassy phase rather than to any change in reaction product.|Substituting sodium carbonate for part of the silicate narrowed the early gap at the cost of 7-day strength.|The practical conclusion is that low-temperature placement is a scheduling problem rather than a durability one.",[2,3],'pos'),
P("Calcined clay–limestone (LC3) blends: hydration kinetics and 28-day performance","Achterberg, S.; Rao, V.; Lindqvist, J.",2024,"Cement and Concrete Composites",
"Limestone calcined clay cement is the most deployable route to substantial clinker reduction, but performance is sensitive to clay purity in ways that are still poorly quantified.|Kaolinitic clays of 42%, 61% and 78% kaolinite content were calcined at 800 °C and blended at a 2:1 clay-to-limestone ratio to a 50% clinker replacement.|Compressive strength at 28 days matched the OPC control at all three purities, with the lowest-purity clay trailing by 4 MPa at 7 days.|Isothermal calorimetry shows the aluminate peak advancing by roughly four hours as kaolinite content rises, consistent with faster carboaluminate formation.|Chloride migration coefficients were approximately halved relative to the control across the series.|The finding that even a 42% kaolinite clay reaches parity at 28 days materially widens the usable feedstock.",[2,3,4],'pos',{seed:true}),
P("Carbonation resistance of geopolymer concrete under accelerated CO₂ exposure","Ferreira, D.; Tan, W.",2024,"Construction and Building Materials",
"Accelerated carbonation testing is the standard durability screen for concrete, but its calibration derives entirely from Portland systems whose pore chemistry differs fundamentally from alkali-activated ones.|Fly-ash/slag geopolymer specimens at three activator moduli were exposed to 3% CO₂ at 65% relative humidity for 180 days alongside a matched OPC control.|Carbonation depth reached 11.2 mm, roughly double the control, while pore-solution alkalinity dropped sharply within the first 28 days and then stabilised.|Natural exposure specimens from a companion series show no comparable divergence after four years.|The authors argue that accelerated protocols systematically overstate the effect for low-calcium systems because the accelerated regime drives a reaction pathway that does not occur at atmospheric concentration.|They propose a modified conditioning step rather than a different limit.",[2,4],'pos',{seed:true}),
/* THE PREPRINT. Same work as the first paper in this list, posted a year earlier
   under a different title, in a different venue, with a different DOI — so it has
   its OWN fingerprint and deduplication cannot touch it. This is the one pair in
   the fixture where opposite labels are not a judgement call but an error, which
   is what the near-duplicate detector exists to catch. */
P("Strength development of alkali-activated slag binders under low-temperature curing","Nkemdirim, R.; Halvorsen, A.",2023,"arXiv (preprint)",
"Placement conditions across northern Europe routinely sit below the 20 °C at which alkali-activated systems are characterised, and the resulting uncertainty is a recognised barrier to adoption on site.|Ground granulated blast-furnace slag activated with sodium silicate was cured at 8, 15 and 20 °C, with strength, calorimetry and pore solution chemistry followed to 90 days.|Mixes reached 41 MPa at 28 days under the coldest regime against 52 MPa at 20 °C, recovering to within 6% by 90 days.|Set was retarded by up to nine hours, attributed to slower dissolution of the glassy phase rather than to any change in reaction product.|The practical conclusion is that low-temperature placement is a scheduling problem rather than a durability one.",[2,3],'pos'),
P("Reactivity of recycled concrete fines as a supplementary cementitious material","Ilesanmi, T.; Grubb, A.; Meier, K.",2024,"Cement and Concrete Research",
"Demolition fines below 150 μm are currently landfilled or used as low-grade fill, despite representing a large and geographically distributed potential feedstock.|Fines from three demolition streams were thermally treated at 500, 650 and 750 °C and characterised by R3 calorimetry, thermogravimetry and mortar testing.|R3 heat release reached 210 J/g at the highest treatment temperature, comparable to a low-grade calcined clay, against essentially zero for untreated material.|Mortar strength at 28 days recovered 88% of the OPC control at 30% replacement.|Dehydroxylation of the residual C-S-H, not the removal of adhered paste, accounts for most of the reactivity gained.|Treatment energy is roughly a third of clinker production per tonne.",[2,3],'pos'),
P("Sulfate resistance of alkali-activated fly ash binders in sodium sulfate solution","Mbeki, N.; Rasmussen, T.",2023,"Cement and Concrete Composites",
"Sulfate attack is the failure mode most often raised against alternative binders in ground-contact applications, and the available data are dominated by short exposures.|Specimens of three fly-ash/slag ratios were immersed in 5% Na₂SO₄ for twelve months with periodic length change, mass and strength measurement.|Expansion stayed below 0.02% throughout against 0.11% for the OPC reference, and no specimen showed visible deterioration.|X-ray diffraction detected no ettringite in any alkali-activated specimen at any age.|The authors attribute the durability to the absence of portlandite and the low calcium content of the binding gel, which removes the reactants the classical mechanism requires.|They caution that magnesium sulfate exposure is a different mechanism and remains untested here.",[2,3,4],'pos'),
P("Magnesium-based cements from reactive MgO: strength and carbonation pathways","Chukwu, A.; Bergström, L.; Vidal, M.",2024,"Cement and Concrete Research",
"Reactive magnesium oxide cements are unusual in that carbonation is the strength-gaining mechanism rather than a durability threat, inverting the framing used for every Portland-derived system.|Specimens were carbonated under 10% CO₂ at 55%, 70% and 85% relative humidity and followed by thermogravimetry and mercury intrusion porosimetry.|Compressive strength reached 34 MPa at 28 days at the intermediate humidity, with hydromagnesite the dominant phase.|Below 55% relative humidity the reaction effectively stalls, which the authors identify as the binding process constraint for precast application.|Total CO₂ uptake was 21% by mass of MgO.|Feedstock availability, not performance, remains the limit on deployment at scale.",[2,3],'pos'),
P("Alkali-silica reaction in alkali-activated concretes: mechanisms and mitigation","Salazar, I.; Björk, T.",2023,"Cement and Concrete Research",
"The high alkali content of activated binders makes alkali-silica reaction an obvious concern, and it is routinely cited as a barrier despite thin evidence either way.|Reactive greywacke aggregate was tested in four alkali-activated systems at 38 °C and 80 °C using both the accelerated mortar bar and concrete prism protocols.|Expansion exceeded the 0.10% threshold in only the highest-alkali formulation, and then only under the 80 °C accelerated regime.|Scanning electron microscopy shows aluminium incorporation into the reaction product, which the authors argue suppresses the swelling behaviour seen in Portland systems.|The standard protocols are shown to be poorly calibrated for these binders because they assume the alkali reservoir is the pore solution alone.|A modified prism test is proposed.",[2,3,4],'pos'),
P("Carbon mineralisation of steel slag for construction aggregate","Delacroix, Y.; Anand, R.",2024,"Journal of CO2 Utilization",
"Basic oxygen furnace slag is produced at roughly 100 kg per tonne of steel and its free lime content makes it both a disposal problem and a carbonation opportunity.|Slag from two mills was carbonated at 0.1, 0.5 and 1.0 MPa CO₂ pressure at ambient temperature, with uptake, volume stability and mechanical properties measured.|Uptake reached 12.8% by mass, sequestering 128 kg CO₂ per tonne of slag.|Carbonated aggregate met EN 12620 requirements for concrete use, and volume stability improved markedly against untreated slag, resolving the expansion that normally disqualifies it.|Concrete made with 100% carbonated slag aggregate reached 38 MPa at 28 days.|The economics depend almost entirely on CO₂ supply cost at the mill.",[2,3],'pos'),
P("Curing regimes for one-part alkali-activated binders: ambient versus heat","Lindgren, A.; Musa, D.",2024,"Construction and Building Materials",
"Two-part alkali-activated systems require handling concentrated alkaline solutions on site, which is the single most cited obstacle to their use outside precast.|Dry-mix one-part formulations using solid sodium metasilicate were evaluated under ambient and 60 °C curing across four precursor blends.|Ambient curing reached 82% of heat-cured 28-day strength, and the gap closed to 94% by 90 days.|Efflorescence was more pronounced under ambient curing but did not affect strength.|Because one-part systems remove the corrosive-liquid handling step entirely, the authors argue the modest strength penalty is the wrong thing to optimise against.|Setting time remains the open problem, ranging from 25 minutes to over four hours across the blends tested.",[2,4],'pos'),
P("Chloride binding in slag-rich binders: a twelve-month marine exposure","Osei, M.; Karlsen, B.",2024,"Cement and Concrete Research",
"Laboratory chloride migration testing is known to correlate imperfectly with field performance, and the divergence is largest precisely for the high-slag binders now being specified for marine structures.|Prisms at 30%, 50% and 70% slag replacement were exposed in the tidal zone for twelve months and profiled alongside laboratory migration specimens.|Apparent diffusion coefficients fell by a factor of four from 30% to 70% replacement, a larger effect than the migration test predicted.|Bound chloride accounted for 38% of total chloride at the highest replacement.|The authors attribute the discrepancy to the migration test's electrical field suppressing binding.|A correction factor is proposed but explicitly labelled provisional on one exposure site.",[2,3],'pos'),
P("Setting behaviour and workability retention of calcined clay systems in hot climates","Ramachandran, S.; Toure, A.",2023,"Cement and Concrete Composites",
"Calcined clay blends are being deployed fastest in exactly the climates where their rapid setting is most problematic, and the admixture guidance available is inherited from Portland practice.|Mixes at 45% replacement were tested at 25 °C, 35 °C and 45 °C with four admixture systems.|Initial set fell from 190 minutes to 68 minutes across the temperature range in the unadmixed control.|A polycarboxylate with an incorporated retarder restored workability retention to 90 minutes at 45 °C without affecting 28-day strength.|Sulfate balancing of the blend proved more effective than admixture dosage alone, which the authors argue is the lever the literature has underweighted.|Field trial data from two sites are included.",[2,3,4],'pos'),
P("Fibre-reinforced geopolymer concrete: flexural performance and fibre-matrix bond","Wienecke, J.; Prasad, N.",2023,"Construction and Building Materials",
"Geopolymer matrices are more brittle than Portland ones, and the fibre-matrix bond that governs post-crack behaviour has been characterised almost entirely in Portland systems.|Steel, polypropylene and basalt fibres were tested at three volume fractions in a fly-ash/slag matrix, with single-fibre pull-out alongside beam testing.|Flexural toughness improved by a factor of 3.4 at 1% steel fibre content.|Pull-out testing shows bond strength 22% higher than in a strength-matched Portland matrix, which the authors attribute to the denser interfacial region.|Basalt fibres degraded measurably in the high-alkalinity pore solution over six months.|The bond advantage means fibre dosages can be lower than Portland practice suggests.",[2,3],'pos'),
P("Thermal activation of dredged sediments as a supplementary cementitious material","Petit-Lund, S.; Ferrara, G.",2024,"Journal of Cleaner Production",
"Port maintenance generates large volumes of fine dredged sediment whose disposal is costly and whose clay content suggests a pozzolanic route.|Sediments from three ports were calcined at 650–850 °C and assessed by R3 calorimetry, strength activity index and leaching testing.|The best-performing sediment reached a strength activity index of 94% at 25% replacement.|Chloride and organic content required a washing step that adds materially to the process cost.|Heavy metal leaching remained below regulatory limits in all cases after binding in the matrix.|The authors are explicit that feedstock variability, not achievable performance, is what would prevent standardisation.",[2,4],'pos'),
P("Autogenous and drying shrinkage of alkali-activated slag: the role of activator modulus","Bergquist, H.; Oyelaran, T.",2023,"Materials and Structures",
"Alkali-activated slag exhibits autogenous shrinkage several times that of Portland concrete, which is the property most likely to cause cracking in restrained structural elements.|Activator modulus was varied from 0.8 to 2.0 across nine mixes with shrinkage followed to 180 days under sealed and drying conditions.|Autogenous shrinkage ranged from 480 to 1,340 microstrain, increasing monotonically with modulus.|Internal curing with pre-wetted lightweight aggregate reduced the highest value by 41%.|Pore size distribution measurements support a capillary-tension mechanism rather than the chemical-shrinkage explanation often assumed.|The practical recommendation is to specify the lowest modulus that meets strength, which is not current practice.",[2,3,4],'pos'),
P("Life-cycle carbon of alkali-activated binders: the activator problem","Nyberg, C.; Sahin, E.",2024,"Journal of Cleaner Production",
"Alkali-activated binders are widely presented as low-carbon, but sodium silicate production is energy-intensive and its allocation dominates the result.|A cradle-to-gate assessment covering twelve formulations was built with primary activator production data rather than the database averages used in most prior work.|Global warming potential ranged from 0.18 to 0.61 tonnes CO₂e per tonne of binder against 0.83 for CEM I.|The highest-performing formulations were not the lowest-carbon ones, and the ranking inverts under a different allocation for slag.|Carbonate activation and one-part solid activators both cut the activator contribution by more than half.|The authors argue that reporting a binder's carbon without its activator route is uninformative.",[2,3,4],'pos'),
P("Bond and development length of reinforcement in high-volume slag concrete","Mancini, D.; Owusu-Ansah, K.",2023,"Engineering Structures",
"Design codes derive bond provisions from Portland concrete, and their extension to binders with different interfacial chemistry is assumed rather than demonstrated.|Ninety pull-out and twelve beam-end specimens were tested at 50% and 70% slag replacement across three cover depths.|Bond strength normalised to compressive strength was 8–14% higher than the Portland control at equal cover.|The improvement tracks the reduced calcium hydroxide content at the steel interface.|Current development length provisions are therefore conservative for these mixes, by a margin the authors quantify.|Cyclic loading was not investigated and is flagged as the gap that would block code adoption.",[2,3],'pos'),
P("Supplementary cementitious materials from bauxite residue: activation and performance","Aliyev, R.; Costa-Mendes, P.",2024,"Cement and Concrete Composites",
"Bauxite residue is generated at roughly 1.2 tonnes per tonne of alumina and is almost entirely stockpiled, making it one of the largest untapped mineral feedstocks.|Residue from two refineries was thermally and mechanically activated and tested at 15–35% replacement.|Thermal activation at 700 °C with a limestone addition gave a strength activity index of 88% at 25% replacement.|Alkalinity and sodium content required a neutralisation step, which the authors cost explicitly.|Radiological screening was within limits for both sources but is noted as source-dependent.|The residue's iron content changes the colour of the finished concrete, which is a commercial rather than technical obstacle.",[2,4],'pos'),
P("Freeze-thaw durability of alkali-activated concrete with and without air entrainment","Halldórsson, P.; Meireles, J.",2023,"Cold Regions Science and Technology",
"Air entrainment in alkali-activated systems is unreliable because conventional admixtures are formulated for Portland pore solutions, leaving freeze-thaw performance an open question in cold climates.|Specimens with four air-entraining systems underwent 300 freeze-thaw cycles with durability factor, scaling and air-void analysis.|Two admixtures produced stable void systems with spacing factors below 200 μm and durability factors above 92.|Non-air-entrained specimens failed before 120 cycles regardless of binder, matching Portland behaviour.|Salt scaling was the more discriminating test and separated the two successful admixtures.|The authors conclude the problem is admixture compatibility rather than any intrinsic limitation of the binder.",[2,3,4],'pos'),
P("Pore structure evolution in limestone calcined clay cement over two years","Ferreiro-Braga, M.; Sandhu, A.",2024,"Cement and Concrete Research",
"Most LC3 characterisation stops at 90 days, yet the refinement that gives these systems their transport resistance continues well beyond that.|Paste and concrete specimens were followed for 24 months by mercury intrusion, nitrogen sorption and electrical resistivity.|Critical pore diameter fell from 42 nm at 28 days to 18 nm at 24 months, with most of the change occurring after 180 days.|Resistivity rose by a factor of 3.8 over the same period against 1.6 for the Portland control.|The continued refinement is attributed to slow pozzolanic reaction of the lower-purity clay fraction.|Service-life models calibrated on 28-day data therefore understate durability substantially for these binders.",[2,3,4],'pos'),
P("Sodium carbonate activation of slag: a lower-carbon activator route","Ndlovu, S.; Ekberg, T.",2023,"Construction and Building Materials",
"Sodium silicate dominates activator carbon footprint, and carbonate activation is the most promising alternative but is limited by slow early strength.|Slag was activated with sodium carbonate alone and with four accelerator additions, followed by calorimetry, strength and phase analysis to 90 days.|Plain carbonate activation gave 8 MPa at 7 days and 44 MPa at 90 days, an unusable early-age profile.|A 3% addition of reactive MgO raised 7-day strength to 27 MPa without affecting the 90-day result.|The mechanism is the removal of carbonate from solution as hydrotalcite, which allows the aluminosilicate reaction to proceed earlier.|Activator carbon footprint falls by roughly 70% against silicate.",[2,3,4],'pos'),
P("Interfacial transition zone in alkali-activated concrete: is it there at all?","Vukovic, N.; Adeoye, B.",2024,"Cement and Concrete Composites",
"The interfacial transition zone is the weakest region of Portland concrete and much mix design is aimed at it, but its existence in alkali-activated systems has been asserted more often than measured.|Nanoindentation grids and backscattered electron image analysis were applied across aggregate interfaces in six alkali-activated and two Portland concretes.|No statistically distinguishable modulus gradient was found in any alkali-activated specimen, against a clear 35 μm gradient in the controls.|Porosity profiles were likewise flat.|The authors attribute this to the absence of a calcium hydroxide preferential deposition mechanism.|If it holds generally, several mix-design rules imported from Portland practice are simply unnecessary here.",[2,3,4],'pos'),
P("Rheology and buildability of low-clinker binders for 3D concrete printing","Haugen, I.; Serrano, P.",2024,"Additive Manufacturing",
"Printable concrete requires a narrow and unusual rheological window, and almost all published formulations depend on high cement contents that undermine the sustainability case for the process.|Yield stress and thixotropic build-up were characterised for four binders at clinker factors of 0.35 to 0.60 using a purpose-built rheometer protocol.|Buildability of 40 layers without collapse was achieved at the lowest clinker factor.|Static yield stress recovered to 1.8 kPa within 60 seconds of shear cessation, which the authors identify as the governing parameter rather than plastic viscosity.|Interlayer bond strength fell 18% at the lowest clinker factor and is the outstanding problem.|A calcined clay–limestone blend gave the best combination overall.",[2,3],'pos'),
/* ── not relevant (46) ─────────────────────────────────────────────── */
P("Life-cycle assessment of Portland-limestone cement in ready-mix supply chains","Duarte, M.; Whitlock, P.",2023,"Journal of Cleaner Production",
"Portland-limestone cement is now the default in several European markets, and its benefit is usually quoted from clinker factor alone.|A cradle-to-gate assessment was built across eleven ready-mix plants in southern Europe using plant-level primary data.|Global warming potential fell 8.4% against CEM I on a per-tonne basis.|Transport contributed less than 6% of total impact in every plant studied, contradicting a common assumption about regional supply.|Variation between plants was larger than the variation between the two cement types.|No claim is made about binder chemistry beyond published clinker factors.",[],'neg'),
P("Marktausblick für die globale Zementindustrie bis 2030","Beaumont, H.; Krüger, T.",2023,"Zement-Kalk-Gips International",
"Die europäische Zementindustrie steht unter dem Druck steigender CO₂-Preise und eines auslaufenden kostenlosen Zuteilungssystems.|Diese Arbeit modelliert die installierte Klinkerkapazität in 44 Märkten unter drei CO₂-Preisszenarien bis 2030.|Die Konsolidierung der sechs größten Hersteller erklärt den Großteil der prognostizierten Kapazitätsänderung.|Importe aus Regionen ohne Kohlenstoffbepreisung steigen in allen Szenarien deutlich an.|Es werden keine experimentellen Arbeiten berichtet.",[],'neg',{tr:'German'}),
P("Retention of dental luting cements: a randomised split-mouth comparison","Okonjo, F.; Bright, S.; Vasquez, L.",2022,"Journal of Prosthetic Dentistry",
"Cement selection for indirect restorations remains contested, with retention rates varying widely between reported series.|Two resin-modified glass ionomer luting cements were compared across 84 crowns in 42 patients using a split-mouth design.|Retention at 24 months was 96.4% and 91.7% respectively, a difference that did not reach significance.|Failure was predominantly adhesive at the cement–dentine interface in both groups.|Preparation taper was a stronger predictor of failure than cement type.",[],'neg'),
P("Optimising truck dispatch in ready-mixed concrete delivery","Sandoval, R.; Klopper, N.",2023,"Automation in Construction",
"Returned concrete represents both a direct cost and an emissions penalty, and dispatch decisions are still largely manual at most plants.|A mixed-integer formulation schedules 60 trucks across 14 plants to minimise waiting time and returned volume.|Returned concrete fell 22% in simulation against the incumbent dispatcher heuristic.|Computation completes within 90 seconds for realistic instance sizes, making it viable for live use.|A three-week field pilot showed a smaller but still significant improvement.",[],'neg'),
P("Compressive behaviour of masonry restored with historic lime mortars","Petrosyan, A.; Doyle, M.",2021,"Journal of Cultural Heritage",
"Repointing historic masonry with incompatible mortars is a well-documented cause of accelerated substrate decay.|Sixteen wall panels were repointed with three lime-based mortars matched to nineteenth-century originals and tested in compression.|Failure loads varied by 31% across mortar types, with the softest mortar giving the lowest panel strength but the least substrate damage.|Compatibility with the historic substrate is prioritised over strength in the authors' recommendations.|Salt transport measurements support the same conclusion.",[],'neg'),
P("Machine learning prediction of concrete compressive strength from mix design","Adeyemi, O.; Lange, F.",2023,"Engineering Applications of Artificial Intelligence",
"Predicting strength from mix proportions would shorten development cycles, and a large body of published mix data now exists to train on.|Gradient boosting, random forests and a multilayer perceptron were compared on 1,030 published mixes with nested cross-validation.|The best model reached R² 0.93 on a held-out split.|Feature importance ranks age and cement content highest, which the authors acknowledge is unsurprising.|Extrapolation beyond the training envelope degraded sharply, which limits use for genuinely novel binders.",[],'neg'),
P("Thermal comfort in naturally ventilated concrete-framed offices","Villanueva, C.; Osei, D.",2022,"Building and Environment",
"Natural ventilation is increasingly specified for its energy benefit, but occupant acceptance in warm-humid climates remains uncertain.|Field measurements and occupant surveys were collected across six buildings over eleven months.|Occupants reported acceptable comfort in 71% of occupied hours.|Thermal mass effects were most pronounced in the shoulder seasons and negligible in peak summer.|Adaptive comfort models fitted the data better than steady-state ones.",[],'neg'),
P("Cement kiln co-processing of refuse-derived fuel","Sørensen, E.; Nakamura, H.",2023,"Waste Management",
"Alternative fuel substitution is the most widely deployed decarbonisation lever available to existing kilns, and its ceiling is set by clinker quality rather than by fuel supply.|Full-scale trials substituted 38% of thermal energy with refuse-derived fuel over six weeks at a 1.4 Mt/y plant.|Free lime and C3S content remained within specification throughout.|NOx fell 12% while total organic carbon in flue gas rose slightly but stayed within permit.|Chlorine bypass dust increased and is identified as the practical constraint on higher substitution.",[],'neg'),
P("Autogenous shrinkage of ultra-high performance concrete with limestone filler","Provost, A.; Ekström, R.",2023,"Materials and Structures",
"Ultra-high performance concrete exhibits large autogenous shrinkage that is difficult to accommodate in restrained elements.|Shrinkage was measured from setting to 90 days on twelve formulations varying filler type and content.|Limestone filler at 15% reduced autogenous shrinkage by roughly a third without a strength penalty.|Internal curing with saturated lightweight sand was more effective still but reduced modulus.|A combined approach gave the best balance across the properties measured.",[],'neg'),
P("Public procurement of low-carbon concrete: a review of specification practice","Nordmann, K.; Reilly, S.",2023,"Building Research & Information",
"Public procurement is frequently proposed as the demand-side lever for low-carbon materials, but its actual use is poorly documented.|Twenty-two public procurement frameworks across nine countries were coded for embodied-carbon requirements.|Only six specify a performance limit rather than a prescriptive mix, and only two require third-party verification.|Prescriptive specification was found to actively exclude several lower-carbon options.|The authors recommend performance specification with independent verification.",[],'neg'),
P("Effect of superplasticiser type on workability retention in high-slag mixes","Ravindran, S.; Køhler, M.",2023,"Construction and Building Materials",
"Admixture compatibility is a recurring practical obstacle in high-replacement mixes and is usually resolved by trial and error on site.|Polycarboxylate and lignosulfonate admixtures were dosed into 60% slag mixes across three cement sources.|Slump retention at 90 minutes was 78% and 41% respectively.|Compatibility with the sulfate balance of the specific cement dominated the result, exceeding the effect of admixture chemistry.|A simple pre-qualification test is proposed.",[],'neg'),
P("Bacterial self-healing concrete: a five-year field exposure","Kirchner, T.; Amofah, P.",2022,"Cement and Concrete Composites",
"Self-healing concrete has been demonstrated repeatedly in the laboratory but field evidence at realistic timescales is scarce.|Encapsulated Bacillus spores were incorporated into precast panels installed at a marine exposure site and monitored for five years.|Crack closure exceeded 0.4 mm width in 68% of monitored cracks against 21% in the control.|Healing effectiveness declined after year three.|Spore viability after five years remains unquantified and is the key uncertainty for service-life claims.",[],'neg'),
P("Fly ash supply under coal phase-out: implications for blended cement production","Ostrowski, J.; Nguyen, H.",2024,"Journal of Cleaner Production",
"Blended cement production in several regions depends on fly ash whose supply is being eliminated by power sector decarbonisation.|Regional fly ash availability is projected to 2040 under announced coal retirement schedules across nine regions.|Supply falls below current blended-cement demand in five of nine regions by 2032.|Stockpile reclamation could bridge part of the gap but its quality is highly variable.|Substitution routes are discussed qualitatively only; no experimental work is reported.",[],'neg'),
P("Digital twins for cement plant energy optimisation: an industrial case study","Fenwick, R.; Iyer, S.",2024,"Applied Energy",
"Process optimisation at existing plants is constrained by the difficulty of experimenting on a running kiln.|A calibrated plant model was deployed at a 1.2 Mt/y facility and operated in advisory mode for nine months.|Specific thermal energy consumption fell 3.1% against the preceding twelve-month baseline.|Model drift required monthly recalibration, which the authors identify as the main barrier to wider deployment.|Operator acceptance was a larger practical obstacle than model accuracy.",[],'neg'),
P("Freeze-thaw durability of concrete with high-volume calcined clay","Marchetti, P.; Osgood, L.",2023,"Cold Regions Science and Technology",
"High-replacement blends are increasingly specified in cold climates where freeze-thaw resistance governs service life.|Specimens underwent 300 freeze-thaw cycles following the standard procedure at three replacement levels.|Durability factors exceeded 90 for air-entrained mixes at 45% replacement.|Non-air-entrained specimens failed before 120 cycles regardless of binder composition.|Air void spacing factor was the controlling parameter throughout, as it is for Portland concrete.",[],'neg'),
P("Occupational silica exposure in concrete cutting: a systematic review","Whelan, B.; Osei-Bonsu, K.",2021,"Annals of Work Exposures and Health",
"Respirable crystalline silica exposure during concrete cutting is a leading occupational health risk in construction.|Thirty-one studies meeting inclusion criteria were pooled and assessed for risk of bias.|Wet cutting reduced exposure by a factor of four to nine across the included studies.|Compliance with exposure limits was reported in fewer than half the studies.|Local exhaust ventilation was less consistently effective than water suppression.",[],'neg'),
P("Interfacial transition zone in recycled aggregate concrete: a microstructural study","Tanaka, R.; Pellegrini, V.",2022,"Cement and Concrete Composites",
"Recycled aggregate concrete contains two interfacial zones, and the older one is generally assumed to govern performance.|Nanoindentation and backscattered electron imaging were applied across three recycled aggregate sources.|The old interfacial zone is consistently weaker than the new one by 18–26% in modulus.|Pre-soaking aggregate narrowed but did not close the gap.|Source variability exceeded the effect of any treatment tested.",[],'neg'),
P("Techno-economic assessment of oxyfuel capture retrofits at cement plants","Grimsby, O.; Achebe, N.",2023,"International Journal of Greenhouse Gas Control",
"Cement process emissions cannot be abated by fuel switching, making capture the only route to deep reduction for existing plants.|Retrofit costs are modelled for three plant configurations in northern Europe with a consistent financial basis.|Levelised cost of capture ranges €62–89 per tonne CO₂ depending on configuration and utilisation.|Air separation unit cost dominates at small plant sizes.|Clinker chemistry is assumed unchanged throughout, which the authors note as a limitation.",[],'neg'),
P("Acoustic emission monitoring of crack propagation in reinforced concrete beams","Halloran, S.; Vermeulen, J.",2022,"Structural Health Monitoring",
"Detecting damage before it is visible would allow intervention at lower cost, and acoustic emission is the most mature candidate technique.|Twelve beams were loaded to failure under four-point bending with distributed acoustic sensors.|Analysis detected macro-crack onset before visible cracking in 10 of 12 beams.|Sensor placement dominated detection reliability, more than any signal processing choice.|Field application remains limited by ambient noise.",[],'neg'),
P("Supplementary cementitious materials from municipal incinerator bottom ash","Ferreiro-Mota, C.; Yilmaz, D.",2024,"Waste Management","",[],'neg',{nab:true}),
P("Corrosion inhibitors for reinforcement in chloride environments: a meta-analysis","Bergqvist, N.; Ohaeri, C.",2021,"Corrosion Science",
"Migrating corrosion inhibitors are widely marketed for repair applications but their field performance is disputed.|Forty-one studies were pooled with a random-effects model and assessed for publication bias.|Effect sizes were heterogeneous and publication bias could not be excluded.|Field performance consistently underperformed laboratory results by a substantial margin.|The authors recommend against specifying inhibitors as a primary protection measure.",[],'neg',{arm:'control'}),
P("Water demand of manufactured sand in mortar applications","Prieto, L.; Aturinde, S.",2022,"Materials and Structures",
"Natural sand scarcity is driving a rapid shift to manufactured sand whose particle shape differs substantially.|Manufactured sands from six quarries were characterised for shape, grading and fines content.|Water demand rose linearly with fines content below 63 μm across all six sources.|Flow table results correlated poorly with rheometer yield stress, questioning the standard acceptance test.|A shape-based correction is proposed.",[],'neg',{arm:'control'}),
P("Seismic retrofit of non-ductile concrete frames using FRP jacketing","Nakagawa, T.; Ilori, B.",2023,"Engineering Structures",
"A large stock of pre-code concrete frames remains in service in seismic regions, and column ductility is typically the governing deficiency.|Four half-scale frames were tested under quasi-static cyclic loading with and without jacketing.|Drift capacity improved from 1.8% to 3.4% with jacketing.|Failure mode shifted from shear to flexure, which is the intended outcome.|Cost per unit of added capacity is reported for two jacket configurations.",[],'neg',{arm:'control'}),
P("Bibliometric analysis of sustainable construction research, 1990–2022","Fadhil, M.; Sørheim, K.",2023,"Sustainability",
"Research output on sustainable construction has grown rapidly and its structure has not been mapped comprehensively.|A corpus of 18,442 records was analysed with co-citation and keyword co-occurrence methods.|Publication volume grew fastest after 2015, coinciding with the Paris Agreement.|China, the USA and the UK dominate output by volume.|Four thematic clusters are identified and their evolution traced.",[],'neg',{arm:'control'}),
P("Carbonation depth prediction in reinforced concrete using probabilistic models","Sundaram, R.; Vejle, K.",2022,"Structural Safety",
"Carbonation-induced corrosion is a dominant deterioration mechanism for inland structures and its prediction remains largely deterministic in practice.|A probabilistic model was calibrated against 340 field measurements from 28 structures.|Predicted service lives were 15–40% shorter than deterministic estimates at the same reliability index.|Exposure classification was the largest source of variance.|The model is offered as a supplement to, not a replacement for, code provisions.",[],'neg'),
P("Recycled tyre rubber as fine aggregate replacement in concrete pavements","Boateng, A.; Lindholm, P.",2023,"Construction and Building Materials",
"End-of-life tyres are a persistent waste stream and rubberised concrete has been proposed repeatedly for pavement applications.|Crumb rubber replaced 5%, 10% and 20% of fine aggregate in a pavement mix.|Compressive strength fell 18% at 10% replacement and 39% at 20%.|Impact resistance and fatigue life improved substantially at all replacement levels.|Surface texture and noise measurements favour the rubberised mixes.",[],'neg'),
P("Cost overruns in large infrastructure concrete works: a database study","Halvorsen, T.; Mutiso, J.",2022,"International Journal of Project Management",
"Cost overruns in infrastructure are extensively documented but rarely disaggregated by work package.|A database of 214 projects was analysed with concrete works isolated as a work package.|Concrete works overran by a median of 14% against a project median of 27%.|Design change was the dominant driver, ahead of material price movement.|Early contractor involvement correlated with lower overruns.",[],'neg'),
P("Sound insulation performance of lightweight concrete partition walls","Deschamps, L.; Ariyo, S.",2021,"Applied Acoustics",
"Lightweight concrete offers thermal and structural advantages but its acoustic performance is often assumed rather than measured.|Nine wall configurations were tested in a transmission suite following the standard procedure.|Weighted sound reduction index ranged from 42 to 54 dB across the configurations.|Cavity depth and lining mass dominated, while concrete density had a smaller effect than expected.|Prediction models overestimated performance by 2–4 dB consistently.",[],'neg'),
P("Photocatalytic cementitious surfaces for urban air quality: a field assessment","Nakamura, Y.; Ferrer, I.",2023,"Building and Environment",
"Titanium dioxide-modified surfaces have been promoted for NOx abatement in urban environments with contested field evidence.|A 900 m² treated pavement was monitored against an untreated control for eighteen months.|NOx reduction averaged 4.2% under favourable conditions and was undetectable otherwise.|Performance declined by half after twelve months due to surface soiling.|The authors conclude the effect is real but too small and too fragile for policy reliance.",[],'neg'),
P("Concrete surface finish quality and formwork release agent selection","Iversen, B.; Chaudhry, N.",2021,"Construction and Building Materials",
"Surface finish defects are a common cause of rework in architectural concrete and release agent selection is largely based on supplier guidance.|Eight release agents were assessed across three formwork materials with standardised visual and colorimetric assessment.|Blowhole area varied by a factor of five between agents on the same formwork.|Vegetable-based agents performed comparably to mineral oils on all substrates.|Application rate mattered more than product chemistry.",[],'neg'),
P("Reinforcement corrosion monitoring using embedded galvanic sensors","Oduya, F.; Trulsson, M.",2022,"Corrosion Science",
"Embedded sensors promise continuous condition data but their long-term reliability in concrete is the limiting factor.|Twenty-four galvanic sensors were embedded in field specimens and monitored for four years.|Sensor drift exceeded the corrosion signal in 7 of 24 units after three years.|Sensors with a reference electrode remained stable throughout.|The authors provide a screening protocol for sensor selection.",[],'neg'),
P("Effect of aggregate mineralogy on concrete thermal expansion","Sarkisian, V.; Odede, B.",2021,"Materials and Structures",
"Thermal expansion coefficient governs restraint stresses in massive elements and is dominated by aggregate rather than paste.|Concretes made with eight aggregate mineralogies were tested from 5 to 60 °C.|Coefficients ranged from 6.8 to 13.1 microstrain per degree.|Quartzitic aggregates gave the highest values, limestone the lowest.|Existing code default values were unconservative for three of the eight.",[],'neg'),
P("Fibre-reinforced polymer reinforcement for concrete: bond durability in alkaline environments","Andriessen, K.; Gomes, R.",2023,"Composites Part B",
"FRP reinforcement avoids corrosion but its long-term bond in a high-alkalinity environment remains the principal durability question.|Specimens were conditioned in simulated pore solution at 20, 40 and 60 °C for up to 24 months and tested in pull-out.|Bond strength retention was 78% at 24 months and 40 °C.|Arrhenius extrapolation gives a 50-year retention of 61%, with wide confidence bounds.|Glass fibre systems degraded substantially faster than basalt or carbon.",[],'neg'),
P("Prefabrication and its effect on construction waste generation","Achterberg, N.; Musonda, I.",2022,"Waste Management",
"Prefabrication is widely claimed to reduce waste but quantified comparisons on matched projects are scarce.|Waste streams were measured on eight matched project pairs across three contractors.|Prefabricated projects generated 42% less waste by mass on site.|Factory waste offset roughly a quarter of that saving, which most prior studies exclude.|Net reduction was 31% when factory waste was included.",[],'neg'),
P("Ultrasonic pulse velocity as a non-destructive strength estimator: a critical appraisal","Villalobos, D.; Iqbal, S.",2021,"NDT & E International",
"Ultrasonic pulse velocity is widely used for in-situ strength estimation despite well-known sensitivity to mix composition.|Correlations were built across 42 mixes spanning four binder types and three aggregate sources.|A single global correlation gave errors of ±38% at the 95% level.|Mix-specific calibration reduced this to ±11%.|The authors argue the method should not be used without calibration on the specific mix, which is rarely done in practice.",[],'neg'),
P("Energy retrofit of concrete panel housing: a post-occupancy evaluation","Lehtinen, O.; Bwalya, C.",2023,"Energy and Buildings",
"Large panel housing represents a substantial share of the European residential stock and its retrofit performance is often modelled rather than measured.|Measured energy use was collected for 340 dwellings before and after retrofit.|Measured savings averaged 34% against a modelled 52%.|Occupant behaviour and pre-retrofit underheating accounted for most of the gap.|The authors recommend adjusting appraisal assumptions accordingly.",[],'neg'),
P("Steel fibre orientation effects in sprayed concrete linings","Rautio, J.; Nwachukwu, E.",2022,"Tunnelling and Underground Space Technology",
"Fibre orientation in sprayed applications is neither random nor controllable, and design provisions assume otherwise.|Computed tomography was used to map fibre orientation in 24 cores from three tunnel linings.|Orientation factors ranged from 0.38 to 0.71 depending on spray angle and distance.|Flexural capacity correlated strongly with the measured orientation factor.|A spray-parameter guidance table is proposed.",[],'neg'),
P("Chemical admixture effects on the air-void system of pumped concrete","Sant'Anna, R.; Volkov, D.",2021,"Cement and Concrete Composites",
"Pumping is known to disturb entrained air but the interaction with admixture chemistry has not been systematically characterised.|Air void parameters were measured before and after pumping on 30 mixes at two pump configurations.|Spacing factor increased by 18–64 μm depending on admixture type.|Polycarboxylate systems were the most affected.|Sampling after the pump rather than at the truck is recommended and is not current practice.",[],'neg'),
P("Concrete recycling logistics: a spatial optimisation of processing plant siting","Dombrowski, P.; Amarasinghe, T.",2023,"Resources, Conservation and Recycling",
"Recycled aggregate use is limited less by technical performance than by the economics of collection and processing.|A spatial optimisation model was applied to three metropolitan regions with real demolition arisings data.|Optimal plant siting reduced transport emissions by 29% against the existing configuration.|Break-even haul distance was 34 km under current gate fees.|Policy levers are ranked by effect size.",[],'neg'),
P("Curing compound efficiency on large horizontal concrete surfaces","Kowalczyk, M.; Byaruhanga, S.",2022,"Construction and Building Materials",
"Curing compounds are specified routinely but their field efficiency is rarely verified.|Nine compounds were assessed on 200 m² slabs under three ambient conditions using moisture loss and surface strength.|Efficiency indices ranged from 52% to 89%.|Application timing affected the result more than product selection.|Two products failed to meet their declared performance under hot-dry conditions.",[],'neg'),
P("Structural health monitoring of concrete bridges using distributed fibre optic sensing","Ferrante, C.; Okonkwo, A.",2024,"Engineering Structures",
"Distributed fibre optic sensing offers spatially continuous strain measurement but installation survival rates in concrete are poorly reported.|Fibre was installed in three bridges during construction and monitored for up to five years.|Survival rate was 84% at five years, with damage concentrated at construction joints.|Measured strain distributions identified two unmodelled restraint effects.|Installation detailing recommendations are given.",[],'neg'),
P("Effect of mixing water quality on concrete properties: recycled and non-potable sources","Zieliński, A.; Ouma, D.",2021,"Journal of Cleaner Production",
"Water scarcity is driving interest in non-potable mixing water whose acceptance criteria date from the 1970s.|Water from six sources including recycled process water was assessed against strength, setting and durability endpoints.|Strength effects were within 5% for all sources tested.|Setting time was affected more, with two sources retarding initial set by over an hour.|Existing acceptance limits were found to be conservative for chloride and unconservative for sulfate.",[],'neg'),
P("Cracking risk in mass concrete foundations: thermal modelling and field validation","Petersen, N.; Rahimi, K.",2022,"Materials and Structures",
"Thermal cracking in mass pours is managed by rules of thumb that predate reliable modelling capability.|A coupled thermal-mechanical model was validated against instrumented pours at four sites.|Predicted peak temperatures were within 3 °C of measurement in all cases.|Cracking risk was governed by surface restraint rather than the core-surface differential in three of four cases.|Current differential-based rules are therefore poorly targeted.",[],'neg'),
P("Barriers to adoption of low-carbon concrete: a survey of specifiers","Whitfield, R.; Nascimento, P.",2023,"Building Research & Information",
"Technical solutions for lower-carbon concrete exist but adoption remains slow, and the reasons are usually asserted rather than surveyed.|A survey of 312 specifiers across five countries was analysed with ordinal regression.|Perceived risk of non-conformance ranked first, ahead of cost and availability.|Familiarity with the standard was the strongest predictor of willingness to specify.|Training, not price, is the lever the results support.",[],'neg'),
P("Abrasion resistance of industrial concrete floors: test method comparison","Grigoriev, S.; Attah, C.",2021,"Construction and Building Materials",
"Three abrasion test methods are in common use and give results that cannot be reconciled.|Twenty-four floor mixes were tested by all three methods alongside a two-year field wear survey.|Method rankings disagreed for 9 of 24 mixes.|Only one method correlated meaningfully with field wear.|The authors recommend that specification cite that method explicitly.",[],'neg'),
P("Embodied carbon benchmarking of structural frames: a database of 200 buildings","Sandoval-Reyes, M.; Tikkanen, H.",2024,"Journal of Cleaner Production",
"Benchmarking is a prerequisite for target setting but published values vary by more than the differences they aim to detect.|A harmonised database of 200 buildings was assembled with consistent system boundaries.|Concrete frames ranged from 210 to 640 kg CO₂e per square metre.|Building height and grid span explained more variance than material choice.|The authors argue benchmarks must be normalised by geometry to be useful.",[],'neg'),
P("Alkali activation of waste glass powder: a preliminary screening","Mensah, K.; Dahlberg, I.",2022,"Waste Management",
"Waste glass is abundant and amorphous, which makes it a plausible precursor despite its low alumina content.|Three glass powders were activated with sodium hydroxide and silicate at four concentrations and tested to 28 days.|Compressive strength reached 21 MPa at best, well below usable structural levels.|Alumina supplementation from metakaolin raised this to 38 MPa.|The authors conclude glass alone is unsuitable as a sole precursor, which is the opposite of several optimistic prior reports.",[],'neg'),
P("Concrete pavement joint sealant performance in cold climates","Lundqvist, E.; Baptiste, J.",2021,"Cold Regions Science and Technology",
"Joint sealant failure admits water and de-icing salts and is a leading cause of pavement deterioration.|Six sealant systems were monitored on in-service pavements over six winters.|Adhesion failure affected 34% of joints by year four in the worst-performing system.|Joint geometry affected performance more than sealant chemistry.|A revised geometry specification is proposed.",[],'neg'),
P("Worker productivity in reinforcement fixing: a time-and-motion study","Berglund, A.; Kimani, W.",2022,"Journal of Construction Engineering and Management",
"Reinforcement fixing is labour-intensive and its productivity assumptions in estimating software date from the 1980s.|Continuous observation was carried out on eleven sites covering 2,400 worker-hours.|Measured productivity was 22% below the standard estimating rate across all sites.|Rebar prefabrication improved the rate by a third where site access allowed it.|Congestion at slab edges accounted for most of the lost time.",[],'neg'),
P("Insurance claims arising from concrete defects: a ten-year portfolio analysis","Nordhagen, T.; Bassey, U.",2023,"Construction Management and Economics",
"Defect claims are a substantial cost to the industry and their distribution across defect types is not publicly documented.|A portfolio of 1,840 claims over ten years was coded by defect type and cause.|Cracking accounted for 41% of claims by number but only 19% by value.|Durability failures were rarer and far more expensive per claim.|Workmanship was the assigned cause in 62% of cases.",[],'neg'),
P("Colour consistency in architectural precast concrete panels","Rasmussen, I.; Cheng, L.",2021,"Construction and Building Materials",
"Visible colour variation between precast panels is a common source of client rejection and is poorly controlled by current specification.|Spectrophotometric measurement was carried out on 340 panels from four plants.|Colour difference exceeded the perceptible threshold on 28% of adjacent panel pairs.|Cement source batch was the dominant factor, ahead of curing and demoulding age.|A batch-tracking protocol is recommended.",[],'neg'),
P("Blast resistance of reinforced concrete panels with polymer overlays","Ekwueme, C.; Sorley, D.",2022,"International Journal of Impact Engineering",
"Retrofit of existing structures against blast is constrained by the added mass conventional strengthening imposes.|Twelve panels with three polymer overlay systems were tested under shock tube loading.|Peak deflection was reduced by up to 44% relative to unstrengthened controls.|Fragment retention was near total for the two elastomeric systems.|Bond to the substrate governed performance and failed prematurely in one system.",[],'neg'),
P("Geotechnical settlement prediction beneath large concrete raft foundations","Iwuchukwu, N.; Halden, M.",2023,"Géotechnique",
"Raft settlement predictions routinely exceed measured values, leading to conservative and costly foundation design.|Predictions from three constitutive models were compared against monitoring data from nine buildings.|All three overpredicted settlement, by factors of 1.4 to 2.9.|Small-strain stiffness selection accounted for most of the discrepancy.|A calibration procedure using site-specific seismic testing is proposed.",[],'neg')
];
PAPERS.forEach((p,i)=>p.id=i);
const POOL=4120, POOL_PREV=.021, BATCH=25;
/* ═══════════════════════════════════════════════════════════════════════
   HOME · the workspace
   ═══════════════════════════════════════════════════════════════════════ */
/* The six live use cases, read from `acagent` on 2026-08-16 — real names, real
   counts, real classifier AUC from model_metrics. Only "Low-carbon cement
   binders" is walkable here; the rest exist so the workspace shows what a
   populated one looks like, which a fabricated list cannot. */
const UCS=[
 {id:1,nm:'Low-carbon cement binders',sub:'cement · alkali-activated · calcined clay',live:true,
  ob:'Find alternative binder chemistries at TRL 4–8 cutting embodied carbon >50%.',
  papers:690,lab:367,pos:170,neg:92,auc:0.886,created:'26 Jun 2026',last:'today'},
 {id:19,nm:'High quality microbial and fungal community in Soil',sub:'soil health · microbiome',
  ob:'Identify research on microbial and fungal community management strategies that enhance soil health.',
  papers:602,lab:602,pos:94,neg:263,auc:null,created:'3 Aug 2026',last:'6 days ago'},
 {id:12,nm:'Named Entity Recognition',sub:'NLP · disambiguation · news',
  ob:'Improve precision, recall and F1 for named entity recognition and disambiguation on news-style content.',
  papers:541,lab:386,pos:223,neg:89,auc:0.656,created:'28 Jul 2026',last:'12 days ago'},
 {id:11,nm:'Solar cells for low earth orbit satellites',sub:'perovskite · silicon · space',
  ob:'Scout perovskite and silicon solar cells, plus the broader review literature on solar in orbit.',
  papers:427,lab:427,pos:276,neg:84,auc:0.660,created:'27 Jul 2026',last:'3 weeks ago'},
 {id:4,nm:'Carbon Capture',sub:'amine · low-temperature · sorbents',
  ob:'Find amine-based carbon capture that operates at lower temperatures without high chemical input.',
  papers:323,lab:323,pos:147,neg:150,auc:0.813,created:'19 Jul 2026',last:'3 weeks ago'},
 {id:20,nm:'Scoring Academic Papers',sub:'LLM scoring · consistency',
  ob:'Achieve low cost, high consistency and high precision in automated scoring of academic works.',
  papers:300,lab:136,pos:29,neg:42,auc:0.881,created:'4 Aug 2026',last:'2 weeks ago'},
 {id:2,nm:'Predicting Technology Developments',sub:'forecasting · TRL · capability',
  ob:'Explore methods for predicting technological breakthroughs in readiness, capability or cost.',
  papers:290,lab:290,pos:157,neg:107,auc:0.741,created:'14 Jul 2026',last:'4 weeks ago'},
 {id:8,nm:'Cleaning microplastics from the gut — bioremediation',sub:'archived',
  ob:'Find promising bioremediation technologies that show high efficacy.',
  papers:130,lab:33,pos:32,neg:0,auc:null,created:'25 Jul 2026',last:'27 Jul 2026',arch:true},
 {id:6,nm:'Potty Training',sub:'archived · negative control',
  ob:'Identify evidence-based techniques that help young children learn to use the toilet.',
  papers:100,lab:5,pos:5,neg:0,auc:null,created:'20 Jul 2026',last:'27 Jul 2026',arch:true}
];

/* Templates: the 28 SYNERGY collections plus the two hand-built ones, read from
   `acagent_demo`. Real paper and positive counts — which is the point: the label
   volume is what tells you whether an example is worth copying from. */
const TEMPLATES=[
 ['Charging infrastructure demand for electric vehicles','v2','Energy · Transport',11865,442,'Empirical and modelling studies quantifying charging infrastructure demand, siting, utilisation or user charging behaviour.'],
 ['Road freight decarbonisation — review landscape','v2','Transport',133,103,'Review, survey and meta-analysis papers covering road freight — electrification, alternative fuels, automation, platooning.'],
 ['Walker 2018 — early-life exposure and offspring effects','v1','Toxicology',48347,761,'Reports that early life exposures produce adverse effects in offspring who were never directly exposed.'],
 ['Brouwer 2019 — relapse in major depressive disorder','v1','Psychology',38114,62,'Psychological factors hypothesised to account for relapse of major depressive disorder.'],
 ['van Dis 2020 — long-term CBT outcomes','v1','Psychology',9128,72,'Long-term outcome evidence for cognitive behavioural therapy in anxiety-related disorders.'],
 ['Hall 2012 — fault prediction in code','v1','Software',8793,104,'Predicting where faults are likely to occur in code, to direct test effort and reduce cost.'],
 ['Wassenaar 2017 — bisphenol A and obesity','v1','Toxicology',7668,111,'Early-life exposure to bisphenol A and its role in the development of obesity.'],
 ['Leenaars 2020 — translational research practice','v1','Medicine',7212,582,'Current practices in translational research, for informed decision making in drug development.'],
 ['Radjenovic 2013 — software metrics for fault prediction','v1','Software',5935,48,'Software metrics used in fault prediction models to improve software quality.'],
 ['Leenaars 2019 — sleep and the prefrontal cortex','v1','Neuroscience',5812,17,'The role of different neurotransmitters in sleep and prefrontal cortex function.'],
 ['Moran 2021 — animal behaviour and physical condition','v1','Ecology',5214,111,'How an individual animal\'s physical condition alters the costs and benefits of risky behaviour.'],
 ['Bos 2018 — small vessel disease and dementia','v1','Medicine',4877,10,'Cerebral small vessel disease and its link to dementia.'],
 ['van de Schoot 2018 — Bayesian analysis uptake','v1','Statistics',4544,38,'Incorporating background knowledge directly into Bayesian analysis.'],
 ['Wolters 2018 — heart disease and dementia risk','v1','Medicine',4278,19,'Whether heart disease predisposes to dementia, beyond shared risk factors.'],
 ['Appenzeller-Herzog 2019 — Wilson disease treatment','v1','Medicine',2841,26,'Comparative effectiveness of treatments for Wilson disease, a rare copper metabolism disorder.'],
 ['Muthu 2021 — robustness of significant outcomes','v1','Medicine',2719,336,'Assessing the robustness of statistically significant outcomes in spine surgery trials.'],
 ['Smid 2020 — Bayesian estimation in small samples','v1','Statistics',2627,27,'Bayesian estimation as an alternative to maximum likelihood in small-sample contexts.'],
 ['van der Waal 2022 — oncology decision making','v1','Medicine',1970,33,'Balancing professional guidance with patient involvement in oncological treatment decisions.'],
 ['Chou 2003 — opioids for chronic non-cancer pain','v1','Medicine',1907,15,'Opioids as appropriate treatment for refractory chronic non-cancer pain under published guidelines.'],
 ['Chou 2004 — skeletal muscle relaxants','v1','Medicine',1630,9,'Skeletal muscle relaxants for spasticity and for musculoskeletal conditions.'],
 ['Jeyaraman 2020 — mesenchymal stem cell sources','v1','Medicine',1175,96,'Efficacy and safety of bone marrow versus adipose-derived mesenchymal stem cells.'],
 ['Menon 2022 — systematic reviews in toxicology','v1','Toxicology',975,74,'Whether systematic reviews function as a gold standard for evidence synthesis in environmental health.'],
 ['Oud 2018 — borderline personality disorder','v1','Psychology',952,20,'Treatment for borderline personality disorder, which affects up to 2% of the population.'],
 ['Meijboom 2021 — biosimilar transitions','v1','Medicine',882,37,'Transitioning patients from an originator biologic to a corresponding biosimilar.'],
 ['van der Valk 2021 — hair glucocorticoids and BMI','v1','Medicine',725,89,'Long-term glucocorticoids measured in scalp hair, against BMI and waist circumference.'],
 ['Nelson 2002 — hormone replacement therapy','v1','Medicine',366,80,'New evidence on the benefits and harms of postmenopausal hormone replacement therapy.'],
 ['Sep 2021 — environmental context in memory','v1','Psychology',271,40,'How information about stable aspects of the environment supports remembering events.'],
 ['Donners 2021 — emicizumab dosing in haemophilia A','v1','Medicine',258,15,'Dosing regimens for emicizumab in people with haemophilia A.']
];
const BENCH2={nm:'Benchset v2', n:200, papers:323903, pos:23697,
  themes:'ten industrial cleantech themes'};
BENCH2.neg=BENCH2.papers-BENCH2.pos; BENCH2.lab=BENCH2.papers;
const SRC=[['OpenAlex',2841],['Crossref',703],['Semantic Scholar',418],['Europe PMC',112],['PubMed',40],['arXiv',6],['CORE',null]];
const STAGES=[['Removing duplicates','4,120 unique of 4,921'],['Reading titles and abstracts','4,120'],
  ['Working out what each one is about','4,120 vectors'],['Sorting by how close they are to your description','done']];

/* ── THE WORKED ANSWER SET ─────────────────────────────────────────────────
   One description, used in three places: the demo strip's "fill the form", the
   landing page (whose charts are scored against it), and `qvec()`, which embeds
   it as the baseline model. Shared rather than duplicated because a landing page
   demonstrating a DIFFERENT use case from the one the app walks through is the
   most avoidable kind of inconsistency — the numbers would silently disagree. */
const DEMO_ANS={
  name:'Low-carbon cement binders',
  kind:'A material or technology',
  systems:['geopolymers','alkali-activated slag','calcined clay','limestone blends'],
  outcome:['compressive strength','carbonation','chloride resistance'],
  numbers:['above 40% clinker replacement','28-day strength'],
  near:['dental cements','plant economics']
};

/* ── THE SIX ───────────────────────────────────────────────────────────────
   The six use cases the landing page presents as "the workspace": the live one
   plus five more, chosen to span the space rather than flatter it — two
   cleantech, one soil biology, one NLP method, one photovoltaics, one
   forecasting. Not the nine in UCS: `Scoring Academic Papers` is this project
   scoring itself and the two archived ones are a stub and a negative control,
   so none of the three belongs in a figure about industrial R&D.

   ONE list, by id, read by three sections — the bubble chart's workspace total,
   the Sankey's pool, and the EDA scatter's selection. They disagreed when each
   held its own copy: the Compare tab resolved its six by name-matching and the
   bubble chart summed all nine, so the same page showed 2,873 papers in one
   figure and 3,403 in another. */
const SIX=[1,19,12,11,4,2];
const sixUcs=()=>SIX.map(id=>UCS.find(u=>u.id===id)).filter(Boolean);

/* ── the welcome, as four slides ──────────────────────────────────────────
   One panel of prose is a thing you skip; four slides with a picture each is a
   thing you click through. The diagrams are deliberately schematic — they are
   drawn from the same primitives as the low-fi labelling animation on the
   landing page, so nothing here impersonates a screenshot of a screen that has
   not been built yet. Copy is FILLER and says so on every slide (Warren is
   writing it); the placeholder is visible rather than lorem, so a reviewer can
   never mistake it for finished text. */
const WSL=[
 {t:'Define your use case',
  d:`<svg viewBox="0 0 300 130"><text class="dg-t" x="8" y="12">YOUR ANSWERS</text>
     ${[0,1,2].map(i=>`<rect class="dg-b" x="8" y="${24+i*22}" width="104" height="13"/>
       <rect class="dg-b" x="8" y="${24+i*22}" width="${44+i*18}" height="13" opacity=".6"/>`).join('')}
     <path class="dg-l" d="M120 51 L156 51" marker-end=""/>
     <path class="dg-l" d="M148 45 L156 51 L148 57"/>
     <rect x="164" y="18" width="128" height="94" fill="hsl(75,20%,98%)" stroke="hsl(145,38%,23%)"
       stroke-opacity=".5"/>
     <text class="dg-t" x="174" y="34">THE DESCRIPTION</text>
     ${[0,1,2,3,4].map(i=>`<rect class="dg-g" x="174" y="${44+i*12}" width="${108-(i%3)*22}" height="4"/>`).join('')}
   </svg>`,
  c:'Six short questions, one at a time. They compile into the description every paper gets matched against — you never type a keyword list.',
  f:'Filler. Should cover: why the description is the highest-leverage thing on the screen, and that it can be changed later without losing your labels.'},
 {t:'Label papers',
  d:`<svg viewBox="0 0 300 130">
     <rect x="106" y="26" width="88" height="78" fill="hsl(75,20%,98%)" stroke="hsl(150,30%,15%)" stroke-opacity=".3"/>
     ${[0,1,2,3].map(i=>`<rect class="dg-b" x="116" y="${38+i*15}" width="${68-(i%2)*20}" height="5"/>`).join('')}
     <g><rect class="dg-r" x="6" y="46" width="70" height="38"/>
       <text class="dg-t" x="41" y="69" text-anchor="middle">NOT FOR ME</text></g>
     <g><rect x="224" y="46" width="70" height="38" fill="hsl(145,38%,23%)" fill-opacity=".16"/>
       <text class="dg-t" x="259" y="69" text-anchor="middle" fill="hsl(145,38%,23%)">RELEVANT</text></g>
     <path class="dg-l" d="M100 65 L80 65 M88 59 L80 65 L88 71"/>
     <path class="dg-l" d="M200 65 L220 65 M212 59 L220 65 L212 71"/>
   </svg>`,
  c:'Two keys, one card at a time. Nothing scores a paper before you have judged it, so your decisions stay yours and the model has something honest to learn from.',
  f:'Filler. Should cover: roughly how many papers, that the order improves as you go, and that a rejection is worth as much as a keep.'},
 {t:'Train your model',
  d:`<svg viewBox="0 0 300 130">
     <path class="dg-d" d="M96 20 C 152 20, 160 110, 104 112"/>
     ${[[62,38],[80,60],[70,82],[54,58],[88,90],[46,74],[74,30],[58,98]].map(([x,y])=>
       `<circle class="dg-g" cx="${x+22}" cy="${y}" r="4.4"/>`).join('')}
     ${[[150,30],[178,52],[206,38],[232,72],[164,96],[198,86],[246,44],[220,106],[256,88],[176,68]].map(([x,y])=>
       `<circle cx="${x}" cy="${y}" r="3.4" fill="hsl(150,12%,50%)" opacity=".45"/>`).join('')}
     <text class="dg-t" x="8" y="14">YOUR KEEPS</text>
     <text class="dg-t" x="196" y="14">THE REST OF THE POOL</text>
   </svg>`,
  c:'Once it has enough examples it fits a model on your labels alone, and reads the whole pool in about a second. It will not work for anyone else’s question — that is the point.',
  f:'Filler. Should cover: what the threshold is and why there is one, and that the model is per-use-case with nothing shared.'},
 {t:'Read less, know more',
  d:`<svg viewBox="0 0 300 130">
     <text class="dg-t" x="8" y="14">EVERYTHING PUBLISHED</text>
     ${[...Array(11)].map((_,i)=>`<rect class="dg-b" x="8" y="${24+i*8}" width="${96-(i%4)*10}" height="5"/>`).join('')}
     <path class="dg-l" d="M120 66 L162 66 M154 60 L162 66 L154 72"/>
     <text class="dg-t" x="176" y="14">WHAT REACHES YOU</text>
     ${[0,1,2].map(i=>`<rect class="dg-g" x="176" y="${48+i*14}" width="${104-i*16}" height="7"/>`).join('')}
     <circle cx="286" cy="18" r="7" fill="none" stroke="hsl(145,38%,23%)" stroke-opacity=".6"/>
     <circle cx="286" cy="18" r="2.4" class="dg-g"/>
   </svg>`,
  c:'From then on it keeps watching and emails you only what clears your bar — which is the whole point of having built it.',
  f:'Filler. Should cover: that alerts are the ongoing value, and what leaves the machine when summarising is on.'}
];
